/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server health check
         * @description Returns server health and database connectivity. 200 when healthy, 503 when degraded.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Resolves the acting user. The pre-auth MVP takes identity from the
         *     `X-User-Id` header and falls back to the seeded designer (张三).
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates
         * @description Offset-paginated list with optional category/status/search filters.
         */
        get: operations["listTemplates"];
        put?: never;
        /**
         * Create a template
         * @description Creates a new draft template and auto-checks it out to the creator.
         *     The creator becomes the lock holder until they check in or an admin force-unlocks.
         */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        /**
         * Get template detail
         * @description Returns the full template including schema and approval_chain.
         */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Save template schema
         * @description Persists the form schema (and optional approval chain). Requires the caller
         *     to be the current lock holder (checked out); otherwise 409 TEMPLATE_LOCKED.
         */
        put: operations["saveTemplateSchema"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out a template
         * @description Acquires the exclusive edit lock. Idempotent for the current holder.
         */
        post: operations["checkoutTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in a template
         * @description Releases the edit lock. Only the holder (or an admin) may check in.
         */
        post: operations["checkinTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a template
         * @description Transitions a draft template to published (atomic status update; clears the lock).
         */
        post: operations["publishTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/force-unlock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force-unlock a template
         * @description Admin-only: clears the edit lock regardless of the current holder. Role enforcement lands with auth (issue 09).
         */
        post: operations["forceUnlockTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error shape returned by the unified error handler and 404 catch-all. */
        ErrorEnvelope: {
            error: {
                /** @description Machine-readable error code, e.g. NOT_FOUND, VALIDATION_ERROR. */
                code: string;
                /** @description Human-readable message (Chinese in the MVP). */
                message: string;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            db: "connected" | "disconnected";
            /** Format: date-time */
            timestamp: string;
            /** @description Process uptime in seconds. */
            uptime: number;
            /** @description Runtime environment, e.g. development, production. */
            env: string;
        };
        /** @description A form template (configuration, not a filled form). Mirrors the form_templates table. */
        FormTemplate: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            category?: string | null;
            /** @description Optimistic-locking version (INT), not the schema format version. */
            version: number;
            /** @description Form structure (JSONB) — sections, fields, validation, conditions. Root contains schemaVersion. */
            schema?: {
                [key: string]: unknown;
            };
            /** @description Approval chain configuration (JSONB) — nodes array. */
            approval_chain?: Record<string, never> | null;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            /** Format: uuid */
            locked_by?: string | null;
            /** Format: date-time */
            locked_at?: string | null;
            /** @description Display name of the current lock holder (resolved for the designer's checkout badge). */
            locked_by_name?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTemplateRequest: {
            /** @description Display name (required). */
            name: string;
            description?: string | null;
            category?: string | null;
            /** @description Initial form structure (JSONB). Defaults to an empty schema. */
            schema?: {
                [key: string]: unknown;
            };
            /** @description Initial approval chain (JSONB). */
            approval_chain?: Record<string, never> | null;
        };
        SaveSchemaRequest: {
            /** @description Form structure (JSONB). Root must contain schemaVersion. */
            schema: {
                [key: string]: unknown;
            };
            /** @description Approval chain (JSONB). Replaces the stored chain when present. */
            approval_chain?: Record<string, never> | null;
        };
        TemplateListResponse: {
            items: components["schemas"]["FormTemplate"][];
            /** @description Total number of templates matching the filters (ignoring pagination). */
            total: number;
            page: number;
            pageSize: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description A filled form submission at runtime. Mirrors the form_instances table. */
        FormInstance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            template_id: string;
            /** @description Frozen copy of the template schema at submission time. */
            template_snapshot: {
                [key: string]: unknown;
            };
            /** @description User-filled field values (JSONB). */
            field_values: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "draft" | "submitted" | "in_approval" | "approved" | "rejected" | "returned" | "withdrawn";
            /** @description Current approval node index (0-based). */
            current_node_index: number;
            /** @description Optimistic-locking version. */
            version: number;
            /** Format: uuid */
            submitted_by?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A single approval node execution record. Mirrors the approval_records table. */
        ApprovalRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instance_id: string;
            /** @description Approval node ID from the approval_chain. */
            node_id: string;
            /** @description Sequential order in the chain. */
            node_order: number;
            /** Format: uuid */
            approver_id?: string | null;
            /** @enum {string} */
            action: "pending" | "approved" | "rejected" | "returned" | "transferred";
            comment?: string | null;
            /** Format: uuid */
            transferred_from?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            acted_at?: string | null;
        };
        /** @description A partially-filled, unsaved form. Independent of FormInstance's draft status (CONTEXT.md "Draft"). */
        Draft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            template_id: string;
            /** Format: uuid */
            user_id: string;
            field_values: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description 2-year retention, after which drafts are purged.
             */
            expires_at: string;
        };
        /** @description A message triggered by a business event. Mirrors the notifications table. */
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            recipient_id: string;
            /** @enum {string} */
            type: "instance_submitted" | "instance_approved" | "instance_rejected" | "instance_returned" | "instance_transferred" | "instance_withdrawn" | "instance_completed";
            title: string;
            content?: string | null;
            /** @description Associated entity type (instance | template). */
            ref_type?: string | null;
            /** Format: uuid */
            ref_id?: string | null;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Correlation ID propagated across logs and echoed in responses. */
        TraceId: string;
        /** @description Client-generated key for idempotent writes (24h window, ADR-0002). */
        IdempotencyKey: string;
        /** @description CSRF token required for mutating methods; read from the xsrf-token cookie. */
        CsrfToken: string;
        /** @description Form template UUID. */
        TemplateId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server and database healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Server up but database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resolved current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                category?: string;
                status?: "draft" | "published" | "archived";
                /** @description Case-insensitive substring match on template name. */
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated template list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Template created and checked out to the creator */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Missing or invalid `name` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    saveTemplateSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSchemaRequest"];
            };
        };
        responses: {
            /** @description Schema saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template locked by someone else or not checked out */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    checkoutTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checked out (or already held by caller) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template already locked by another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    checkinTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lock released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template locked by another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    publishTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template is not in draft status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    forceUnlockTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lock cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
