/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server health check
         * @description Returns server health and database connectivity. 200 when healthy, 503 when degraded.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Resolves the acting user. The pre-auth MVP takes identity from the
         *     `X-User-Id` header and falls back to the seeded designer (张三).
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates
         * @description Offset-paginated list with optional category/status/search filters.
         */
        get: operations["listTemplates"];
        put?: never;
        /**
         * Create a template
         * @description Creates a new draft template and auto-checks it out to the creator.
         *     The creator becomes the lock holder until they check in or an admin force-unlocks.
         */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        /**
         * Get template detail
         * @description Returns the full template including schema and approval_chain.
         */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Save template schema
         * @description Persists the form schema (and optional approval chain). Requires the caller
         *     to be the current lock holder (checked out); otherwise 409 TEMPLATE_LOCKED.
         */
        put: operations["saveTemplateSchema"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out a template
         * @description Acquires the exclusive edit lock. Idempotent for the current holder.
         */
        post: operations["checkoutTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in a template
         * @description Releases the edit lock. Only the current holder may check in (admin override lands with auth, issue 09).
         */
        post: operations["checkinTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a template
         * @description Transitions a draft template to published (atomic status update; clears the lock).
         */
        post: operations["publishTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/force-unlock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force-unlock a template
         * @description Admin-only: clears the edit lock regardless of the current holder. Role enforcement lands with auth (issue 09).
         */
        post: operations["forceUnlockTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published forms
         * @description Lists the forms a filler can start — only *published* templates. Supports
         *     category + search filters and offset pagination.
         */
        get: operations["listForms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a draft instance
         * @description Starts a new form for a published template. The instance begins in `draft` status.
         */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my instances
         * @description Drafts and submissions owned by the acting user, newest first. Optional
         *     comma-separated status filter.
         */
        get: operations["listMyInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        /**
         * Get instance detail
         * @description Returns the instance plus its approval records and the live template.
         *     Drafts render against `template.schema`; submitted instances carry a frozen
         *     `template_snapshot`.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/values": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Autosave field values
         * @description Persists field values on a draft instance without bumping the optimistic
         *     lock version. Rejects non-draft instances.
         */
        put: operations["saveInstanceValues"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an instance
         * @description Validates the field values against the current template schema and
         *     atomically submits (ADR-0001): the instance update, frozen snapshot, and
         *     approval-record inserts commit together; approver resolution runs inside
         *     that transaction. Notifications persist async after commit.
         */
        post: operations["submitInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw a submitted instance
         * @description Reverts a `submitted`/`in_approval` instance back to draft. Optimistic
         *     locking on `version` (409 VERSION_CONFLICT); rejected if any approver has
         *     already acted (400 APPROVAL_NOT_PENDING).
         */
        post: operations["withdrawInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my drafts
         * @description Offset-paginated drafts owned by the acting user, newest first.
         */
        get: operations["listDrafts"];
        put?: never;
        /**
         * Create a draft
         * @description Saves a lightweight draft for a published template.
         */
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft UUID. */
                id: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        /**
         * Resume a draft
         * @description Returns the draft with best-effort fieldId migration against the current
         *     template schema (ADR-0004): still-valid fields are kept, removed fields
         *     move to `_orphaned`, and `version_mismatch` flags when anything moved.
         */
        get: operations["getDraft"];
        /**
         * Update a draft
         * @description Replaces the draft's field values.
         */
        put: operations["updateDraft"];
        post?: never;
        /**
         * Discard a draft
         * @description Deletes the draft. Returns 204 on success.
         */
        delete: operations["deleteDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Verifies email + password, then issues a httpOnly JWT (`access_token`,
         *     Secure + SameSite=Strict) and a JS-readable CSRF token (`xsrf-token`).
         *     Rate-limited to 5 requests per minute per client IP.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the session (sliding expiration)
         * @description Exchanges the current token for a fresh 7-day token.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Clears the access_token and xsrf-token cookies.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description The authenticated user with their roles and permission codes.
         */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description All roles with their permission codes. Requires admin:manage_roles.
         */
        get: operations["listRoles"];
        put?: never;
        /**
         * Create a role
         * @description Creates a role with at least one permission code.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Role UUID. */
                id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Update a role
         * @description Replaces name/description and optionally the permission codes.
         */
        put: operations["updateRole"];
        post?: never;
        /**
         * Delete a role
         * @description Deletes the role and cascades its user/permission assignments.
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List permission codes
         * @description The 20 predefined permission codes, grouped by category.
         */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Users with their assigned roles. Requires admin:manage_users.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** Get a user's roles */
        get: operations["getUserRoles"];
        put?: never;
        /**
         * Replace a user's roles
         * @description Replaces the user's role set (capabilities are the union).
         */
        post: operations["setUserRoles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error shape returned by the unified error handler and 404 catch-all. */
        ErrorEnvelope: {
            error: {
                /** @description Machine-readable error code, e.g. NOT_FOUND, VALIDATION_ERROR. */
                code: string;
                /** @description Human-readable message (Chinese in the MVP). */
                message: string;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            db: "connected" | "disconnected";
            /** Format: date-time */
            timestamp: string;
            /** @description Process uptime in seconds. */
            uptime: number;
            /** @description Runtime environment, e.g. development, production. */
            env: string;
        };
        /** @description A form template (configuration, not a filled form). Mirrors the form_templates table. */
        FormTemplate: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            category?: string | null;
            /** @description Optimistic-locking version (INT), not the schema format version. */
            version: number;
            /** @description Form structure (JSONB) — sections, fields, validation, conditions. Root contains schemaVersion. */
            schema?: {
                [key: string]: unknown;
            };
            /** @description Approval chain configuration (JSONB) — nodes array. */
            approval_chain?: Record<string, never> | null;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            /** Format: uuid */
            locked_by?: string | null;
            /** Format: date-time */
            locked_at?: string | null;
            /** @description Display name of the current lock holder (resolved for the designer's checkout badge). */
            locked_by_name?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTemplateRequest: {
            /** @description Display name (required). */
            name: string;
            description?: string | null;
            category?: string | null;
            /** @description Initial form structure (JSONB). Defaults to an empty schema. */
            schema?: {
                [key: string]: unknown;
            };
            /** @description Initial approval chain (JSONB). */
            approval_chain?: Record<string, never> | null;
        };
        SaveSchemaRequest: {
            /** @description Form structure (JSONB). Root must contain schemaVersion. */
            schema: {
                [key: string]: unknown;
            };
            /** @description Approval chain (JSONB). Replaces the stored chain when present. */
            approval_chain?: Record<string, never> | null;
        };
        TemplateListResponse: {
            items: components["schemas"]["FormTemplate"][];
            /** @description Total number of templates matching the filters (ignoring pagination). */
            total: number;
            page: number;
            pageSize: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description The authenticated user with roles, permission codes, and (on login/refresh) the CSRF token. */
        AuthResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            roles: components["schemas"]["RoleSummary"][];
            /** @description Union of permission codes across the user's roles. */
            permissions: string[];
            /** @description Fresh CSRF token echoed in the body (also set as the xsrf-token cookie). */
            csrfToken?: string;
        };
        RoleSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
        };
        Role: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** @description Permission codes assigned to this role. */
            permissions: string[];
            /** Format: date-time */
            created_at?: string;
        };
        RoleRequest: {
            name: string;
            description?: string | null;
            /** @description At least one permission code is required on create. */
            permissionCodes: string[];
        };
        RoleListResponse: {
            items: components["schemas"]["Role"][];
        };
        Permission: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            category: string;
        };
        PermissionListResponse: {
            items: components["schemas"]["Permission"][];
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            is_active: boolean;
            roles: components["schemas"]["RoleSummary"][];
        };
        UserListResponse: {
            items: components["schemas"]["AdminUser"][];
        };
        RoleAssignmentRequest: {
            roleIds: string[];
        };
        /** @description A filled form submission at runtime. Mirrors the form_instances table. */
        FormInstance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            template_id: string;
            /** @description Frozen copy of the template schema at submission time. */
            template_snapshot: {
                [key: string]: unknown;
            };
            /** @description User-filled field values (JSONB). */
            field_values: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "draft" | "submitted" | "in_approval" | "approved" | "rejected" | "returned" | "withdrawn";
            /** @description Current approval node index (0-based). */
            current_node_index: number;
            /** @description Optimistic-locking version. */
            version: number;
            /** Format: uuid */
            submitted_by?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A single approval node execution record. Mirrors the approval_records table. */
        ApprovalRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instance_id: string;
            /** @description Approval node ID from the approval_chain. */
            node_id: string;
            /** @description Sequential order in the chain. */
            node_order: number;
            /** Format: uuid */
            approver_id?: string | null;
            /** @enum {string} */
            action: "pending" | "approved" | "rejected" | "returned" | "transferred";
            comment?: string | null;
            /** Format: uuid */
            transferred_from?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            acted_at?: string | null;
        };
        /** @description A partially-filled, unsaved form. Independent of FormInstance's draft status (CONTEXT.md "Draft"). */
        Draft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            template_id: string;
            /** Format: uuid */
            user_id: string;
            field_values: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description 2-year retention, after which drafts are purged.
             */
            expires_at: string;
        };
        /** @description A message triggered by a business event. Mirrors the notifications table. */
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            recipient_id: string;
            /** @enum {string} */
            type: "instance_submitted" | "instance_approved" | "instance_rejected" | "instance_returned" | "instance_transferred" | "instance_withdrawn" | "instance_completed";
            title: string;
            content?: string | null;
            /** @description Associated entity type (instance | template). */
            ref_type?: string | null;
            /** Format: uuid */
            ref_id?: string | null;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description A reduced template view embedded in instance/draft detail responses. */
        TemplateSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            schema: {
                [key: string]: unknown;
            };
            approval_chain?: Record<string, never> | null;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A published form in the form center list. */
        FormSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            category?: string | null;
            schema: {
                [key: string]: unknown;
            };
            approval_chain?: Record<string, never> | null;
            /** Format: date-time */
            updated_at: string;
        };
        FormListResponse: {
            items: components["schemas"]["FormSummary"][];
            total: number;
            page: number;
            pageSize: number;
        };
        /** @description An approval record with the approver's display name resolved. */
        ApprovalRecordSummary: {
            /** Format: uuid */
            id: string;
            node_id: string;
            node_order: number;
            /** Format: uuid */
            approver_id?: string | null;
            approver_name?: string | null;
            /** @enum {string} */
            action: "pending" | "approved" | "rejected" | "returned" | "transferred";
            comment?: string | null;
            /** Format: date-time */
            acted_at?: string | null;
        };
        /** @description A FormInstance enriched with approval progress and the live template. */
        InstanceDetail: components["schemas"]["FormInstance"] & {
            approval_records: components["schemas"]["ApprovalRecordSummary"][];
            template: components["schemas"]["TemplateSummary"];
        };
        /** @description A FormInstance with the template display name resolved. */
        InstanceListItem: components["schemas"]["FormInstance"] & {
            template_name?: string | null;
        };
        InstanceListResponse: {
            items: components["schemas"]["InstanceListItem"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateInstanceRequest: {
            /** Format: uuid */
            template_id: string;
            /** @description Optional initial field values. */
            field_values?: {
                [key: string]: unknown;
            };
        };
        SaveValuesRequest: {
            field_values: {
                [key: string]: unknown;
            };
        };
        SubmitRequest: {
            /** @description Final values to submit; defaults to the last autosaved values. */
            field_values?: {
                [key: string]: unknown;
            };
        };
        WithdrawRequest: {
            /** @description Expected optimistic-lock version (required); a mismatch yields 409 VERSION_CONFLICT. */
            version: number;
        };
        /** @description A draft after version-mismatch migration, with the live template attached. */
        DraftDetail: components["schemas"]["Draft"] & {
            /** @description Values whose fieldId no longer exists in the current schema. */
            _orphaned?: {
                [key: string]: unknown;
            };
            /** @description True when at least one value was orphaned by migration. */
            version_mismatch: boolean;
            template: components["schemas"]["TemplateSummary"];
        };
        /** @description A draft with the template display name resolved. */
        DraftListItem: components["schemas"]["Draft"] & {
            template_name?: string | null;
        };
        DraftListResponse: {
            items: components["schemas"]["DraftListItem"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateDraftRequest: {
            /** Format: uuid */
            template_id: string;
            field_values?: {
                [key: string]: unknown;
            };
        };
        UpdateDraftRequest: {
            field_values: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Correlation ID propagated across logs and echoed in responses. */
        TraceId: string;
        /** @description Client-generated key for idempotent writes (24h window, ADR-0002). */
        IdempotencyKey: string;
        /** @description CSRF token required for mutating methods; read from the xsrf-token cookie. */
        CsrfToken: string;
        /** @description Form template UUID. */
        TemplateId: string;
        /** @description Form instance UUID. */
        InstanceId: string;
        /** @description Draft UUID. */
        DraftId: string;
        /** @description Role UUID. */
        RoleId: string;
        /** @description User UUID. */
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server and database healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Server up but database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resolved current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                category?: string;
                status?: "draft" | "published" | "archived";
                /** @description Case-insensitive substring match on template name. */
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated template list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Template created and checked out to the creator */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Missing or invalid `name` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    saveTemplateSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSchemaRequest"];
            };
        };
        responses: {
            /** @description Schema saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template locked by someone else or not checked out */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    checkoutTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checked out (or already held by caller) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template already locked by another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    checkinTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lock released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template locked by another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    publishTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template is not in draft status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    forceUnlockTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form template UUID. */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lock cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplate"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listForms: {
        parameters: {
            query?: {
                category?: string;
                /** @description Case-insensitive substring match on form name. */
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of published forms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormListResponse"];
                };
            };
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstanceRequest"];
            };
        };
        responses: {
            /** @description Draft instance created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetail"];
                };
            };
            /** @description Template not published */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listMyInstances: {
        parameters: {
            query?: {
                /** @description Comma-separated status filter, e.g. `draft,submitted`. */
                status?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of the user's instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceListResponse"];
                };
            };
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetail"];
                };
            };
            /** @description Instance not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    saveInstanceValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveValuesRequest"];
            };
        };
        responses: {
            /** @description Values saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormInstance"];
                };
            };
            /** @description Instance is not in draft status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not the owner of the instance */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Instance not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submitInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Submitted (status submitted, or approved when no approvers) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetail"];
                };
            };
            /** @description Not a draft/withdrawn instance or template not published */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not the owner of the instance */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Already submitted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Field validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Approver resolution failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    withdrawInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Form instance UUID. */
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WithdrawRequest"];
            };
        };
        responses: {
            /** @description Withdrawn (back to draft) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetail"];
                };
            };
            /** @description Not a withdrawable status, or an approver already acted */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not the owner of the instance */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Optimistic-lock version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listDrafts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of drafts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftListResponse"];
                };
            };
        };
    };
    createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Template not published */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft UUID. */
                id: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft (migrated) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetail"];
                };
            };
            /** @description Draft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft UUID. */
                id: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDraftRequest"];
            };
        };
        responses: {
            /** @description Draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Draft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft UUID. */
                id: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Draft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; returns the user with roles + permissions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Wrong credentials (uniform, no user enumeration) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing email or password */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            /** @description Missing admin:manage_roles */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description Role created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Missing admin:manage_roles */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid name or permission codes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Role UUID. */
                id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description Role updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Role UUID. */
                id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permission catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionListResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    getUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    setUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID. */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignmentRequest"];
            };
        };
        responses: {
            /** @description The user's new roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
