/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server health check
         * @description Returns server health and database connectivity. 200 when healthy, 503 when degraded.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error shape returned by the unified error handler and 404 catch-all. */
        ErrorEnvelope: {
            error: {
                /** @description Machine-readable error code, e.g. NOT_FOUND, VALIDATION_ERROR. */
                code: string;
                /** @description Human-readable message (Chinese in the MVP). */
                message: string;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            db: "connected" | "disconnected";
            /** Format: date-time */
            timestamp: string;
            /** @description Process uptime in seconds. */
            uptime: number;
            /** @description Runtime environment, e.g. development, production. */
            env: string;
        };
        /** @description A form template (configuration, not a filled form). Mirrors the form_templates table. */
        FormTemplate: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            category?: string | null;
            /** @description Optimistic-locking version (INT), not the schema format version. */
            version: number;
            /** @description Form structure (JSONB) — sections, fields, validation, conditions. Root contains schemaVersion. */
            schema?: {
                [key: string]: unknown;
            };
            /** @description Approval chain configuration (JSONB) — nodes array. */
            approval_chain?: Record<string, never> | null;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            /** Format: uuid */
            locked_by?: string | null;
            /** Format: date-time */
            locked_at?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A filled form submission at runtime. Mirrors the form_instances table. */
        FormInstance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            template_id: string;
            /** @description Frozen copy of the template schema at submission time. */
            template_snapshot: {
                [key: string]: unknown;
            };
            /** @description User-filled field values (JSONB). */
            field_values: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "draft" | "submitted" | "in_approval" | "approved" | "rejected" | "returned" | "withdrawn";
            /** @description Current approval node index (0-based). */
            current_node_index: number;
            /** @description Optimistic-locking version. */
            version: number;
            /** Format: uuid */
            submitted_by?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A single approval node execution record. Mirrors the approval_records table. */
        ApprovalRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instance_id: string;
            /** @description Approval node ID from the approval_chain. */
            node_id: string;
            /** @description Sequential order in the chain. */
            node_order: number;
            /** Format: uuid */
            approver_id?: string | null;
            /** @enum {string} */
            action: "pending" | "approved" | "rejected" | "returned" | "transferred";
            comment?: string | null;
            /** Format: uuid */
            transferred_from?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            acted_at?: string | null;
        };
        /** @description A partially-filled, unsaved form. Independent of FormInstance's draft status (CONTEXT.md "Draft"). */
        Draft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            template_id: string;
            /** Format: uuid */
            user_id: string;
            field_values: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description 2-year retention, after which drafts are purged.
             */
            expires_at: string;
        };
        /** @description A message triggered by a business event. Mirrors the notifications table. */
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            recipient_id: string;
            /** @enum {string} */
            type: "instance_submitted" | "instance_approved" | "instance_rejected" | "instance_returned" | "instance_transferred" | "instance_withdrawn" | "instance_completed";
            title: string;
            content?: string | null;
            /** @description Associated entity type (instance | template). */
            ref_type?: string | null;
            /** Format: uuid */
            ref_id?: string | null;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Correlation ID propagated across logs and echoed in responses. */
        TraceId: string;
        /** @description Client-generated key for idempotent writes (24h window, ADR-0002). */
        IdempotencyKey: string;
        /** @description CSRF token required for mutating methods; read from the xsrf-token cookie. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server and database healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Server up but database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
